name: Generate script tests
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          pip install pytest
      - name: Run tests
        run: |
          pytest tests -vvv